volumes:
  surmai_data:

services:
  surmai:
    container_name: surmai_server
    image: surmai:golang-build
    build:
      dockerfile: ./Dockerfile
    volumes:
      - surmai_data:/pb_data
    ports:
      - "9090:8080"
    restart: always
    environment:
      SURMAI_ADMIN_EMAIL: admin@surmai.net
      SURMAI_ADMIN_PASSWORD: ChangeMe123#@!