name: Docker Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Login to the Container registry
      uses: docker/login-action@v2
      with:
        registry: http://192.168.68.104:13000
        username: rohit
        password: ${{ secrets.CI_TOKEN }}
    - name: Build and push Docker image
      uses: https://github.com/docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: "192.168.68.104:13000/rohit/surmai:${{gitea.sha}},192.168.68.104:13000/rohit/surmai:latest"

